resolvers:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 9.9.9.10
  - 77.88.8.8
  - 77.88.8.1
  - 208.67.222.222
  - 208.67.220.220
sources:
  - alienvault
  - archiveis
  - asnlookup
  - binaryedge
  - bufferover
  - builtwith
  - censys
  - certspotter
  - certspotterold
  - commoncrawl
  - crtsh
  - dnsdumpster
  - dnsdb
  - entrust
  - fullhunt
  - github
  - hunterhow
  - hackertarget
  - ipv4info
  - intelx
  - leakix
  - passivetotal
  - rapiddns
  - securitytrails
  - shodan
  - sitedossier
  - spyse
  - sublist3r
  - threatcrowd
  - threatminer
  - urlscan
  - virustotal
  - waybackarchive
  - zoomeye
asnlookup: [cde9f861a9msh4bfadef91c38098p186648jsn40be4dfe9ee3]
binaryedge: []
builtwith: [1c7b5942-7e41-4c3b-bde1-f1ed21bfde2d]
censys: [dd12937f-df89-4221-9080-45ac952f6f86, 8tBnmVC2AL5H71w25tqkVJigaUTgDTzj]
certspotter: [k52752_TUCNBvpYpzrcDkF8iKk5]
chaos: []
dnsdb: []
fullhunt: [ef5bc6c0-b4cd-479a-bf88-b2cd48ca7359]
github: []
hunterhow: [fb0026aad8aa1a253b76bf07bd2e05cc9780b573134c245490c71ab0b165b9d1]
intelx: []
leakix: [MxKLSKlLtEIvlCjy6KGuQ2Yai9lebP0I6vfyTc6ffyFT_fPC]
passivetotal: []
securitytrails: [bydgDn-UNthzg3lrZOoS6lXJIVFmK3wb]
shodan: [tXmKCZwtDBYsLZYcR3jDlnNe1KPJqLWV]
spyse: []
urlscan: []
virustotal: [358a49f4feb9455165844d75ebcc2a549282825eb4cf5be998fc4d9e5ae333fa]
zoomeye: []
